### ISSUE TITLE
keys and values

### ISSUE THREAD

**Issue by initialneil** [b0nes164/ShaderOneSweep#1]
Great work!

The current `b_sort` is the `keys` to be sorted. How can we perform a `key & value` sort? i.e. the value array is arranged by the sorting of the keys.

**Comment by b0nes164** [comment]
Hi @initialneil,

I haven't implemented a key and value version, *yet*. However, I believe it would be only a small modification from the `key` only implementation. Basically once the `keys` are scattered in device memory, use the offsets which are still in registers to scatter the `values` into shared memory, then scatter the runs of `values` from shared memory to device.

**Comment by initialneil** [comment]
@b0nes164 Thanks for the reply. I try to modify `BlockRadixSort.compute` accordingly.
1. Change BIN_PART_SIZE smaller to fit another group shared memory
```
#define BIN_PART_SIZE       3840 
#define BIN_THREADS         480  
#define BIN_SUB_PART_SIZE   256  
#define BIN_SUB_PART_LOG    8    
#define BIN_WAVES           15   

RWBuffer<uint> b_sortPayload;
RWBuffer<uint> b_altPayload;

groupshared uint g_wavePayloads[BIN_PART_SIZE];    //Shared memory for the per wave payload

```
2. mimic keys to set payloads
```
//read
const int t = LANE + BIN_SUB_PART_START + BIN_PART_START;
uint4 firstKeys;
firstKeys.x = b_sort[t];
firstKeys.y = b_sort[t + 32];
firstKeys.z = b_sort[t + 64];
firstKeys.w = b_sort[t + 96];
uint4 firstPayloads;                              // adding
firstPayloads.x = b_sortPayload[t];               // adding
firstPayloads.y = b_sortPayload[t + 32];          // adding
firstPayloads.z = b_sortPayload[t + 64];          // adding
firstPayloads.w = b_sortPayload[t + 96];          // adding
        
uint4 secKeys;
secKeys.x = b_sort[t + 128];
secKeys.y = b_sort[t + 160];
secKeys.z = b_sort[t + 192];
secKeys.w = b_sort[t + 224];
uint4 secPayloads;                                // adding
secPayloads.x = b_sortPayload[t + 128];           // adding
secPayloads.y = b_sortPayload[t + 160];           // adding
secPayloads.z = b_sortPayload[t + 192];           // adding
secPayloads.w = b_sortPayload[t + 224];           // adding
```
3. set payloads
```
//Scatter keys into shared memory
//For some bizarre reason, this is signicantly faster rolled 
for (int i = 0; i < 4; ++i)
{
    g_waveHists[firstOffsets[i]] = firstKeys[i];
    g_waveHists[secOffsets[i]] = secKeys[i];
    g_wavePayloads[firstOffsets[i]] = firstPayloads[i];    // adding
    g_wavePayloads[secOffsets[i]] = secPayloads[i];        // adding
}
GroupMemoryBarrierWithGroupSync();
        
//Scatter runs of keys into device memory;
for (int i = GROUP_THREAD_ID; i < BIN_PART_SIZE; i += BIN_THREADS)
{
    firstKeys.x = g_waveHists[i];
    firstKeys.y = firstKeys.x & RADIX_MASK;
    firstKeys.z = g_localHist[firstKeys.y] + i;
    b_alt[firstKeys.z] = firstKeys.x;
    b_altPayload[firstKeys.z] = g_wavePayloads[i];         // adding
}
GroupMemoryBarrierWithGroupSync();
```
4. for extra numbers
```
b_alt[offset] = key;
b_altPayload[offset] = b_sortPayload[i];        // adding
```
-----
I have tested the code by setting the payload to the index of the array and checked the sorted index. It all works! Below attached is the payload version of `BlockRadixSortPayload`.
[BlockRadixSortPayload.compute.txt](https://github.com/b0nes164/ShaderOneSweep/files/12465428/BlockRadixSortPayload.compute.txt)

-----
The `OneSweep.compute` has an additional *Lookback* region that's beyond my understanding...

**Comment by b0nes164** [comment]
Wow that was really fast, I was honestly not expecting a response so soon! However, there is a better way to do this.

Instead of altering the size of the partition tile, we make the observation that the `value` never needs to be read from device memory until it is ready to be scattered. This has two implications: One, we can scatter the `values` directly into shared memory; Two, we can perform the `value` scattering *after* the `key` scattering, thus allowing us to use the full shared memory without modification. 

This is important for performance because we don't have to cut the number of active waves per threadblock, `BIN_WAVES`, we can maintain a larger shared memory partition tile size, and we don't need additional registers.

To do this, we first modify the device level `key` scattering so that we store the device scattering `offset` in the `key` register. Because we already scattered the key into shared memory, it is safe to overwrite the register:
```HLSL
//Scatter runs of keys into device memory, manually unrolled
{
    int i = LANE + BIN_SUB_PART_START;
    firstKeys.x = g_localHist[g_waveHists[i] & RADIX_MASK] + i;
    b_alt[firstKeys.x] = g_waveHists[i];
    
    . . .
    . . .
    
    i += LANE_COUNT
    secKeys.w = g_localHist[g_waveHists[i] & RADIX_MASK] + i;
    b_alt[secKeys.w] = g_waveHists[i];
}
GroupMemoryBarrierWithGroupSync();
```

Because we have scattered the keys, we can now overwrite the shared memory:
```HLSL
//Scatter payload directly into shared memory
{
    g_waveHists[firstOffsets.x] = b_sortPayload[t]
    g_waveHists[firstOffsets.y] = b_sortPayload[t + 32]
    g_waveHists[firstOffsets.z] = b_sortPayload[t + 64]
    g_waveHists[firstOffsets.w] = b_sortPayload[t + 96]

    g_waveHists[secOffsets.x] = b_sortPayload[t + 128]
    g_waveHists[secOffsets.y] = b_sortPayload[t + 160]
    g_waveHists[secOffsets.z] = b_sortPayload[t + 192]
    g_waveHists[secOffsets.w] = b_sortPayload[t + 224]
}
GroupMemoryBarrierWithGroupSync();
```


Now using the device scattering offset we saved, we scatter the payload:
```HLSL
//Scatter runs of keys into device memory, manually unrolled
{
    int i = LANE + BIN_SUB_PART_START;
    b_altPayload[firstKeys.x] = g_waveHists[i];
    
    . . .
    . . .
    
    i += LANE_COUNT
    b_altPayload[secKeys.w] = g_waveHists[i];
}
GroupMemoryBarrierWithGroupSync();
```

I plan on releasing an updated version of the sorts soon, which will simplify things and will also include the key and value implementation, so if you wait a couple days (hopefully) I'll have those out.

**Comment by b0nes164** [comment]
Alright, the key value implementation for the single threadblock sort is on the repo now! I should have the implementation for _OneSweep_ out soon.

**Comment by b0nes164** [comment]
Alright, the key value implementation for _OneSweep_ is now on the repo, let me know if you have any other questions.

**Comment by bentoboxlimited** [comment]
This implementation is brilliant and simple. I've tried reading through the cub implementation and wow. This is so much better. 

I was hoping you could answer a question for me about the block of code below. 

```

uint4 bits = countbits(firstOffsets << LANE_MASK - LANE);
        int index = (firstKeys.x & RADIX_MASK) + (WAVE_INDEX << RADIX_LOG);
        uint prev = g_waveHists[index];
        if (bits.x == 1)
            g_waveHists[index] += countbits(firstOffsets.x);
        firstOffsets.x = prev + bits.x - 1;

```

Here is where you are calculating the wave offsets by using the `WaveActiveBallot` to check whether the thread pulled a key with a set bit. 

But what is the code block above doing? I don't understand - for example - why you check to see if the counted bit is 1. The lane mask in the first few lines is also puzzling to me as it seems to shift away all of the bits in the lowest lanes. 

Would you mind if I try my hand at implementing a version of your code in Metal? MSL is sorely lacking in freely available algorithms such as this one and your implementation is really impressive.

**Comment by b0nes164** [comment]
Hi @bentoboxlimited, please create a new issue for a separate topic, see the new issue I just opened.

**Comment by b0nes164** [comment]
Key-Value pair sorting functionality added.
