### ISSUE TITLE
Warp Level Multisplit

### ISSUE THREAD

**Issue by b0nes164** [b0nes164/ShaderOneSweep#2]
This implementation is brilliant and simple. I've tried reading through the cub implementation and wow. This is so much better. 

I was hoping you could answer a question for me about the block of code below. 

```

uint4 bits = countbits(firstOffsets << LANE_MASK - LANE);
        int index = (firstKeys.x & RADIX_MASK) + (WAVE_INDEX << RADIX_LOG);
        uint prev = g_waveHists[index];
        if (bits.x == 1)
            g_waveHists[index] += countbits(firstOffsets.x);
        firstOffsets.x = prev + bits.x - 1;

```

Here is where you are calculating the wave offsets by using the `WaveActiveBallot` to check whether the thread pulled a key with a set bit. 

But what is the code block above doing? I don't understand - for example - why you check to see if the counted bit is 1. The lane mask in the first few lines is also puzzling to me as it seems to shift away all of the bits in the lowest lanes. 

Would you mind if I try my hand at implementing a version of your code in Metal? MSL is sorely lacking in freely available algorithms such as this one and your implementation is really impressive.

_Originally posted by @bentoboxlimited in https://github.com/b0nes164/ShaderOneSweep/issues/1#issuecomment-1702007152_

**Comment by b0nes164** [comment]
Feel free to implement the code in Metal, the only thing I ask is that you credit me, link to this repo, and include the original BSD-3 license from CUB as Nvidia is still the copyright holder of the algorithm.

Now, to answer the first question:

Our sort is a *least-significant-digit* radix sort (_LSD_). That means we performing counting sort passes starting from the least-significant digit, up to the most significant digit (_MSD_). Unlike _MSD_ sorts. an _LSD_ sort ***must be stable*** to function. That means that keys of an equivalent digit value must be scattered in the same relative order as in the original input during a pass.

So here is the issue: To save on register memory requirements, each warp shares a portion of shared memory to accumulate digit counts for the counting sort, we call this the *warp histogram*. Now, let's imagine, we have an Nvidia card which has a warp-width of 32 an each thread in our warp has the following keys:

```
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5
```
Each of the first sixteen threads have a key of value 0, and the last 16 threads have a key value of 5. In order for the sort to be stable, each thread needs to know if any lower rank thread in the warp also has a key with the same value, so that the keys are scattered in the same relative order. To solve this, we use a modified version of Ashkiani et. al.'s [Multisplit](https://arxiv.org/abs/1701.01189). I highly recommend reading the paper and attempting to implement the algorithm yourself, otherwise what I'm saying won't make much sense. To put it simply, all multisplit does is create a warp-width value where each bit indicates whether a thread shares a key with other threads of the warp. So going back to our example, the bitwise value produced by multisplit for key value 0 would be 
```
00000000000000001111111111111111
```
because the first sixteen threads share the same value, 0. Because each thread knows its own index in the warp, we can calculate the number of preceding keys that share the same value by shifting away all higher rank bits, then counting the remaining bits. So for example, we want to get preceding count for thread number 5:

First we shift away `31 - 4 = 27` bits like so (this is `firstOffsets << LANE_MASK - LANE`):
```
00000000000000001111111111111111 << 27 
//equals 11111000000000000000000000000000
```
Now, by counting the bits that remain, we know that there are 4 preceding threads, and so the correct, stable offset for this thread should be 4:
 ```
 countbits(11111000000000000000000000000000) - 1
 //equals 4
 ```
 By counting the number of unshifted bits we get the total digit count for the warp, which a single thread then adds to the *warp-histogram*
 ```
 countbits(00000000000000001111111111111111)
//equals 16
 ```
 
 So to recap multisplit does two things:

1.  It determines the correct per-thread offset if threads share a key value.

2. It determines the total count of a given key value in a warp, and safely increments the histogram in shared memory.

--- 

In Ashkiani's original implementation multisplit was performed for ***every digit of the radix***. That means for an 8-bit radix, the `WaveActiveBallot` operation was performed for all 256 digits. Resulting in:
$$\left\lceil \frac{digitCount}{warpWidth} \right\rceil \log_2(digitCount)$$
`WaveActiveBallot` operations. However, this is wasteful. By the pigeonholing principle we know that at most, there can only be ***warp-width*** number of keys present, meaning that at most we should only be performing: 
$$\left\lceil \frac{warpWidth}{warpWidth} \right\rceil \log_2(digitCount) = \log_2(digitCount)$$
`WaveActiveBallot` operations. 

The issue is accomplishing goal number two of multisplit: determining the total count of the warp. Since we are no longer checking *every* key value, how do we know which value to increment in the histogram? And how do we make sure that only single thread increments the histogram value? 

The trick is to realize that we can determine the correct key value to increment in the *warp histogram* simply by retrieving the key value from a thread's register. The second trick is to realize that only one thread will have a shifted bit count of 1, for any given key, and so by checking if 
```
if(bits == 1)
```
we guarantee that only a single thread increments the histogram for a given key value, thus ensuring it is safely updated.

**Comment by bentoboxlimited** [comment]
Fantastic thanks for the detailed explanation. I'll definitely add a Metal implementation to my do to list and link back here.

**Comment by b0nes164** [comment]
Good luck! If you haven't done so already, make sure to pull the latest version of the repo because I refactored the code, so it should be significantly more readable now!
