### ISSUE TITLE
Key Value improperly sorting input sizes not multiples of the partition tile size

### ISSUE THREAD

**Issue by b0nes164** [b0nes164/ShaderOneSweep#4]
#3
> Currently `BlockRadixSortKeyValue` works perfectly fine, but `OneSweepKeyValue` has an issue.
> In `OneSweepKeyValue` when the size is not dividable by `partitionSize`, the sorting result is unreliable.

**Comment by b0nes164** [comment]
Hi @initialneil,

I'm having difficulty reproducing the bug. I tested the key-value sort at all input sizes from 7680000 to 7687680, which effectively covers all non-partition tile sizes. At what input sizes were you getting this bug, and were you using the helper to dispatch the kernels or the original?

**Comment by b0nes164** [comment]
Could not replicate issue, and non-response from issue source. Suspected cause is that the incorrect host helper function was used to verify the sort.

**Comment by initialneil** [comment]
@b0nes164 thanks for checking out, I was using helper function. Sorry I am caught up in projects, I'll double check the helper to see if I did something wrong. Many thanks.
