### ISSUE TITLE
Feature request: nearest neighbor search

### ISSUE THREAD

**Issue by jackguo709** [b0nes164/ShaderOneSweep#5]
Hey Thomas, thanks for your work! Have you considered looking into nearest neighbor search algorithms in 3D? It'll be very valuable for a lot of projects.

**Comment by b0nes164** [comment]
Hi @jackguo709, I'm not super familiar with nearest neighbor problems, could you point me towards a paper or blog post describing the problem? Needless to say, it's not something on my radar at the moment. I am *guessing* you are referring to a spatial partitioning technique like what is described in 32.2 [here](https://developer.nvidia.com/gpugems/gpugems3/part-v-physics-simulation/chapter-32-broad-phase-collision-detection-cuda), where objects are hashed into "spatial cells", then the cells are sorted?
