### ISSUE TITLE
minimum e_size

### ISSUE THREAD

**Issue by segmation** [b0nes164/ShaderOneSweep#6]
Is there a minimum size for the array to be sorted?  In OneSweepKeyValue.compute seems like G_HIST_PART_SIZE gets set to zero if e_size is smaller than G_HIST_TBLOCKS (2048).

thanks!

**Comment by b0nes164** [comment]
Yes, there is an issue with minimum sizes; the divisions should be division round up. The fixes for this issue will be rolled out in a Unity package I am working on.
